name: "Fritz!Box Mesh Overview"
version: "2.0.0"
slug: "fritz_mesh_overview"
description: "Zeigt die Fritz!Box Mesh Ãœbersicht (kompatibel mit FritzOS 8.0+ via Browser-Emulation)."
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
map:
  - "8000:8000"
options:
  fritz_host: "http://fritz.box"
  fritz_pass: "DeinPasswort"
  refresh_rate: 10
schema:
  fritz_host: str
  fritz_pass: password
  refresh_rate: int
image: "tillitschshock/fritz-mesh-overview-{arch}"