name: "Fritz!Box Mesh Overview"
version: "3.0.0"
slug: "fritzmesh"
description: "Interaktive Live-Steuerung deiner Fritz!Box Mesh-Netzwerk (FritzOS 8.0+ kompatibel)"
url: "https://github.com/TillitschScHocK/FRITZ-Box-Mesh-Overview"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: application
boot: auto
ports:
  8000/tcp: 8000
ports_description:
  8000/tcp: "Web-Interface Port"
webui: "http://[HOST]:[PORT:8000]/"
options:
  fritz_host: "fritz.box"
  fritz_pass: ""
  fritz_user: "Admin"
schema:
  fritz_host: str
  fritz_pass: password
  fritz_user: str
